services:
    zookeeper:
        image: docker.io/bitnami/zookeeper:3.9
        volumes:
            - "august-tv-zookeeper:/bitnami"
        environment:
            - ZOOKEEPER_CLIENT_PORT=2181
            - ZOOKEEPER_TICK_TIME=2000
            - ALLOW_ANONYMOUS_LOGIN=yes
    kafka:
        image: docker.io/bitnami/kafka:3.4
        ports:
            - "9092:9092"
        volumes:
            - "august-tv-kafka:/bitnami"
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_LISTENERS=LISTENER_INTERNAL://0.0.0.0:9092,LISTENER_EXTERNAL://0.0.0.0:9093
            - KAFKA_ADVERTISED_LISTENERS=LISTENER_INTERNAL://localhost:9092,LISTENER_EXTERNAL://kafka:9093
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
            - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_INTERNAL
        depends_on:
            - zookeeper
    kafka-ui:
        image: docker.io/provectuslabs/kafka-ui:latest
        ports:
            - "8090:8080"
        environment:
            - KAFKA_CLUSTERS_0_NAME=kafka-cluster
            - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9093
            - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
        depends_on:
            - kafka
            - zookeeper
    postgres:
        image: docker.io/library/postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: august-tv

volumes:
    august-tv-zookeeper:
        driver: local
    august-tv-kafka:
        driver: local
